
-- description generated by Pat driver

--			date     : Fri Nov 24 18:56:16 2017
--			revision : v109

--			sequence : reg

-- input / output list :
in       clk B;;
in       reset B;;
in       data (31 downto 0) X;;
out      s (31 downto 0) X;;
in       vdd B;;
in       vss B;;

begin

-- Pattern description :

--                         c r d         s        v v  
--                         l e a                  d s  
--                         k s t                  d s  
--                           e a                       
--                           t                         


-- Beware : unprocessed patterns

<          0 ps>         : 0 0 00000000 ?******** 1 0 ;
<          1 ps>         : 1 0 00000000 ?00000000 1 0 ;
<          2 ps>         : 0 0 ffffffff ?00000000 1 0 ;
<          3 ps>         : 1 0 ffffffff ?ffffffff 1 0 ;
<          4 ps>         : 0 0 aabbccdd ?ffffffff 1 0 ;
<          5 ps>         : 1 0 aabbccdd ?aabbccdd 1 0 ;
<          6 ps>         : 0 0 01010101 ?aabbccdd 1 0 ;
<          7 ps>         : 1 0 01010101 ?01010101 1 0 ;
<          8 ps>         : 0 0 cccccccc ?01010101 1 0 ;
<          9 ps>         : 1 0 cccccccc ?cccccccc 1 0 ;
<         10 ps>         : 0 0 77777777 ?cccccccc 1 0 ;
<         11 ps>         : 1 0 77777777 ?77777777 1 0 ;
<         12 ps>         : 0 0 88888888 ?77777777 1 0 ;
<         13 ps>         : 1 0 88888888 ?88888888 1 0 ;
<         14 ps>         : 0 0 10101010 ?88888888 1 0 ;
<         15 ps>Reset_15 : 1 0 10101010 ?10101010 1 0 ;
<         16 ps>         : 0 1 10101010 ?10101010 1 0 ;
<         17 ps>         : 1 1 10101010 ?00000000 1 0 ;

end;
